### ISSUE TITLE
Author misrepresented?

### ISSUE THREAD

**Issue by OlafvdSpek** [OmniBlade/ccmix#2]
Hi Blade,

How are ya doing?
In CBlowfish.cpp and other files I see `Author: ivosh-l`.
Some files look a bit like files I've written though..

https://github.com/OmniBlade/ccmix/blob/master/src/CBlowfish.cpp
https://github.com/OlafvdSpek/xcc/blob/master/misc/blowfish.cpp

**Comment by OmniBlade** [comment]
Hello

Apologies, I believe this is from the repo that I forked ccmix from and is certainly not something I've intentionally done. The master branch is pretty much defunct now, at some point I will merge the crypto branch in where that file has been removed in favour of using the crypto++ library to provide blowfish support.

**Comment by OmniBlade** [comment]
Branches merged.

**Comment by OlafvdSpek** [comment]
I was actually curious about that crypto code, hehe.

**Comment by OmniBlade** [comment]
I spent ages working out what the XCC code actually did, I suspected it was RSA but didn't know for sure until I finally figured out how to load the public and private keys into an RSA library. I've actually since reimplemented the original header encryption for RA++. The big int code was a C interface called XMP and looks to be heavily based upon early PGP code implementing RSA. The header was written and read by stream classes called PKPipe and PKStraw which wrapped the big int RSA code and the blowfish code into a seamless stream interface that hid all the encryption implementation, you just used those classes to read and write data and all the rest was hidden.

**Comment by OlafvdSpek** [comment]
RA++? Haven't heard about it before, but looks very interesting!

**Comment by OmniBlade** [comment]
Its mostly driven by CCHyper to develop an accurate reimplementation of the RA engine, but he doesn't want to release it until its further along and in some minimally playable state. I've started a similar project for Zero Hour called thyme but using the original binary to develop it along similar lines to OpenRCT2's development if you are familiar with it. That is being developed in an open manner though so the source so far is already available.

**Comment by OlafvdSpek** [comment]
I'm aware of OpenTTD, OpenDune and Ares, didn't see OpenRCT2 or Thyme before either. Having a fully usable version from day 1 is very nice, the main problem with RA2 I've had is that it's so hard to call into existing functions.

**Comment by OmniBlade** [comment]
What calling convention does it use? __stdcall? System I use for thyme is a bit more straight forward than ares, it just patches jumps to the start of a function to replace one and you just convert the address for an existing one to a function pointer and call it to call original versions. Works nicely as long as the game loads to a consistent base address. Look at hooker.h and dllmain.cpp in thyme for examples of how it works. I believe ares uses debugging functions to hook the and replace functions, but its been a while since I tried to figure out how it worked. The method I use is more like Tiberian Technologies Renegade Scripts dll.

**Comment by OlafvdSpek** [comment]
Calling etc works fine, but defining all those functions is so much work.

**Comment by OmniBlade** [comment]
Yeah, its a fair amount of grunt work depending on what you are wanting to achieve.
